// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"cambridge-hit.com/gin-base/activateserver/app/entity/ent/device"
	"cambridge-hit.com/gin-base/activateserver/app/entity/ent/licensetype"
	"cambridge-hit.com/gin-base/activateserver/app/entity/ent/licensetypefeatures"
	"cambridge-hit.com/gin-base/activateserver/app/entity/ent/predicate"
	"cambridge-hit.com/gin-base/activateserver/app/entity/ent/product"
	"cambridge-hit.com/gin-base/activateserver/app/entity/ent/productfeature"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LicenseTypeQuery is the builder for querying LicenseType entities.
type LicenseTypeQuery struct {
	config
	ctx                     *QueryContext
	order                   []licensetype.OrderOption
	inters                  []Interceptor
	predicates              []predicate.LicenseType
	withProduct             *ProductQuery
	withFeatures            *ProductFeatureQuery
	withDevices             *DeviceQuery
	withLicenseTypeFeatures *LicenseTypeFeaturesQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LicenseTypeQuery builder.
func (ltq *LicenseTypeQuery) Where(ps ...predicate.LicenseType) *LicenseTypeQuery {
	ltq.predicates = append(ltq.predicates, ps...)
	return ltq
}

// Limit the number of records to be returned by this query.
func (ltq *LicenseTypeQuery) Limit(limit int) *LicenseTypeQuery {
	ltq.ctx.Limit = &limit
	return ltq
}

// Offset to start from.
func (ltq *LicenseTypeQuery) Offset(offset int) *LicenseTypeQuery {
	ltq.ctx.Offset = &offset
	return ltq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ltq *LicenseTypeQuery) Unique(unique bool) *LicenseTypeQuery {
	ltq.ctx.Unique = &unique
	return ltq
}

// Order specifies how the records should be ordered.
func (ltq *LicenseTypeQuery) Order(o ...licensetype.OrderOption) *LicenseTypeQuery {
	ltq.order = append(ltq.order, o...)
	return ltq
}

// QueryProduct chains the current query on the "product" edge.
func (ltq *LicenseTypeQuery) QueryProduct() *ProductQuery {
	query := (&ProductClient{config: ltq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ltq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ltq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(licensetype.Table, licensetype.FieldID, selector),
			sqlgraph.To(product.Table, product.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, licensetype.ProductTable, licensetype.ProductColumn),
		)
		fromU = sqlgraph.SetNeighbors(ltq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFeatures chains the current query on the "features" edge.
func (ltq *LicenseTypeQuery) QueryFeatures() *ProductFeatureQuery {
	query := (&ProductFeatureClient{config: ltq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ltq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ltq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(licensetype.Table, licensetype.FieldID, selector),
			sqlgraph.To(productfeature.Table, productfeature.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, licensetype.FeaturesTable, licensetype.FeaturesPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(ltq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDevices chains the current query on the "devices" edge.
func (ltq *LicenseTypeQuery) QueryDevices() *DeviceQuery {
	query := (&DeviceClient{config: ltq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ltq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ltq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(licensetype.Table, licensetype.FieldID, selector),
			sqlgraph.To(device.Table, device.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, licensetype.DevicesTable, licensetype.DevicesColumn),
		)
		fromU = sqlgraph.SetNeighbors(ltq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryLicenseTypeFeatures chains the current query on the "license_type_features" edge.
func (ltq *LicenseTypeQuery) QueryLicenseTypeFeatures() *LicenseTypeFeaturesQuery {
	query := (&LicenseTypeFeaturesClient{config: ltq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ltq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ltq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(licensetype.Table, licensetype.FieldID, selector),
			sqlgraph.To(licensetypefeatures.Table, licensetypefeatures.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, licensetype.LicenseTypeFeaturesTable, licensetype.LicenseTypeFeaturesColumn),
		)
		fromU = sqlgraph.SetNeighbors(ltq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first LicenseType entity from the query.
// Returns a *NotFoundError when no LicenseType was found.
func (ltq *LicenseTypeQuery) First(ctx context.Context) (*LicenseType, error) {
	nodes, err := ltq.Limit(1).All(setContextOp(ctx, ltq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{licensetype.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ltq *LicenseTypeQuery) FirstX(ctx context.Context) *LicenseType {
	node, err := ltq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LicenseType ID from the query.
// Returns a *NotFoundError when no LicenseType ID was found.
func (ltq *LicenseTypeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ltq.Limit(1).IDs(setContextOp(ctx, ltq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{licensetype.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ltq *LicenseTypeQuery) FirstIDX(ctx context.Context) int {
	id, err := ltq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LicenseType entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one LicenseType entity is found.
// Returns a *NotFoundError when no LicenseType entities are found.
func (ltq *LicenseTypeQuery) Only(ctx context.Context) (*LicenseType, error) {
	nodes, err := ltq.Limit(2).All(setContextOp(ctx, ltq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{licensetype.Label}
	default:
		return nil, &NotSingularError{licensetype.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ltq *LicenseTypeQuery) OnlyX(ctx context.Context) *LicenseType {
	node, err := ltq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LicenseType ID in the query.
// Returns a *NotSingularError when more than one LicenseType ID is found.
// Returns a *NotFoundError when no entities are found.
func (ltq *LicenseTypeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ltq.Limit(2).IDs(setContextOp(ctx, ltq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{licensetype.Label}
	default:
		err = &NotSingularError{licensetype.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ltq *LicenseTypeQuery) OnlyIDX(ctx context.Context) int {
	id, err := ltq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LicenseTypes.
func (ltq *LicenseTypeQuery) All(ctx context.Context) ([]*LicenseType, error) {
	ctx = setContextOp(ctx, ltq.ctx, "All")
	if err := ltq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*LicenseType, *LicenseTypeQuery]()
	return withInterceptors[[]*LicenseType](ctx, ltq, qr, ltq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ltq *LicenseTypeQuery) AllX(ctx context.Context) []*LicenseType {
	nodes, err := ltq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LicenseType IDs.
func (ltq *LicenseTypeQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ltq.ctx.Unique == nil && ltq.path != nil {
		ltq.Unique(true)
	}
	ctx = setContextOp(ctx, ltq.ctx, "IDs")
	if err = ltq.Select(licensetype.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ltq *LicenseTypeQuery) IDsX(ctx context.Context) []int {
	ids, err := ltq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ltq *LicenseTypeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ltq.ctx, "Count")
	if err := ltq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ltq, querierCount[*LicenseTypeQuery](), ltq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ltq *LicenseTypeQuery) CountX(ctx context.Context) int {
	count, err := ltq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ltq *LicenseTypeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ltq.ctx, "Exist")
	switch _, err := ltq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ltq *LicenseTypeQuery) ExistX(ctx context.Context) bool {
	exist, err := ltq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LicenseTypeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ltq *LicenseTypeQuery) Clone() *LicenseTypeQuery {
	if ltq == nil {
		return nil
	}
	return &LicenseTypeQuery{
		config:                  ltq.config,
		ctx:                     ltq.ctx.Clone(),
		order:                   append([]licensetype.OrderOption{}, ltq.order...),
		inters:                  append([]Interceptor{}, ltq.inters...),
		predicates:              append([]predicate.LicenseType{}, ltq.predicates...),
		withProduct:             ltq.withProduct.Clone(),
		withFeatures:            ltq.withFeatures.Clone(),
		withDevices:             ltq.withDevices.Clone(),
		withLicenseTypeFeatures: ltq.withLicenseTypeFeatures.Clone(),
		// clone intermediate query.
		sql:  ltq.sql.Clone(),
		path: ltq.path,
	}
}

// WithProduct tells the query-builder to eager-load the nodes that are connected to
// the "product" edge. The optional arguments are used to configure the query builder of the edge.
func (ltq *LicenseTypeQuery) WithProduct(opts ...func(*ProductQuery)) *LicenseTypeQuery {
	query := (&ProductClient{config: ltq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ltq.withProduct = query
	return ltq
}

// WithFeatures tells the query-builder to eager-load the nodes that are connected to
// the "features" edge. The optional arguments are used to configure the query builder of the edge.
func (ltq *LicenseTypeQuery) WithFeatures(opts ...func(*ProductFeatureQuery)) *LicenseTypeQuery {
	query := (&ProductFeatureClient{config: ltq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ltq.withFeatures = query
	return ltq
}

// WithDevices tells the query-builder to eager-load the nodes that are connected to
// the "devices" edge. The optional arguments are used to configure the query builder of the edge.
func (ltq *LicenseTypeQuery) WithDevices(opts ...func(*DeviceQuery)) *LicenseTypeQuery {
	query := (&DeviceClient{config: ltq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ltq.withDevices = query
	return ltq
}

// WithLicenseTypeFeatures tells the query-builder to eager-load the nodes that are connected to
// the "license_type_features" edge. The optional arguments are used to configure the query builder of the edge.
func (ltq *LicenseTypeQuery) WithLicenseTypeFeatures(opts ...func(*LicenseTypeFeaturesQuery)) *LicenseTypeQuery {
	query := (&LicenseTypeFeaturesClient{config: ltq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ltq.withLicenseTypeFeatures = query
	return ltq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TypeName string `json:"type_name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LicenseType.Query().
//		GroupBy(licensetype.FieldTypeName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ltq *LicenseTypeQuery) GroupBy(field string, fields ...string) *LicenseTypeGroupBy {
	ltq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LicenseTypeGroupBy{build: ltq}
	grbuild.flds = &ltq.ctx.Fields
	grbuild.label = licensetype.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TypeName string `json:"type_name,omitempty"`
//	}
//
//	client.LicenseType.Query().
//		Select(licensetype.FieldTypeName).
//		Scan(ctx, &v)
func (ltq *LicenseTypeQuery) Select(fields ...string) *LicenseTypeSelect {
	ltq.ctx.Fields = append(ltq.ctx.Fields, fields...)
	sbuild := &LicenseTypeSelect{LicenseTypeQuery: ltq}
	sbuild.label = licensetype.Label
	sbuild.flds, sbuild.scan = &ltq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LicenseTypeSelect configured with the given aggregations.
func (ltq *LicenseTypeQuery) Aggregate(fns ...AggregateFunc) *LicenseTypeSelect {
	return ltq.Select().Aggregate(fns...)
}

func (ltq *LicenseTypeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ltq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ltq); err != nil {
				return err
			}
		}
	}
	for _, f := range ltq.ctx.Fields {
		if !licensetype.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ltq.path != nil {
		prev, err := ltq.path(ctx)
		if err != nil {
			return err
		}
		ltq.sql = prev
	}
	return nil
}

func (ltq *LicenseTypeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*LicenseType, error) {
	var (
		nodes       = []*LicenseType{}
		_spec       = ltq.querySpec()
		loadedTypes = [4]bool{
			ltq.withProduct != nil,
			ltq.withFeatures != nil,
			ltq.withDevices != nil,
			ltq.withLicenseTypeFeatures != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*LicenseType).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &LicenseType{config: ltq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ltq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ltq.withProduct; query != nil {
		if err := ltq.loadProduct(ctx, query, nodes, nil,
			func(n *LicenseType, e *Product) { n.Edges.Product = e }); err != nil {
			return nil, err
		}
	}
	if query := ltq.withFeatures; query != nil {
		if err := ltq.loadFeatures(ctx, query, nodes,
			func(n *LicenseType) { n.Edges.Features = []*ProductFeature{} },
			func(n *LicenseType, e *ProductFeature) { n.Edges.Features = append(n.Edges.Features, e) }); err != nil {
			return nil, err
		}
	}
	if query := ltq.withDevices; query != nil {
		if err := ltq.loadDevices(ctx, query, nodes,
			func(n *LicenseType) { n.Edges.Devices = []*Device{} },
			func(n *LicenseType, e *Device) { n.Edges.Devices = append(n.Edges.Devices, e) }); err != nil {
			return nil, err
		}
	}
	if query := ltq.withLicenseTypeFeatures; query != nil {
		if err := ltq.loadLicenseTypeFeatures(ctx, query, nodes,
			func(n *LicenseType) { n.Edges.LicenseTypeFeatures = []*LicenseTypeFeatures{} },
			func(n *LicenseType, e *LicenseTypeFeatures) {
				n.Edges.LicenseTypeFeatures = append(n.Edges.LicenseTypeFeatures, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ltq *LicenseTypeQuery) loadProduct(ctx context.Context, query *ProductQuery, nodes []*LicenseType, init func(*LicenseType), assign func(*LicenseType, *Product)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*LicenseType)
	for i := range nodes {
		fk := nodes[i].ProductID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(product.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "product_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (ltq *LicenseTypeQuery) loadFeatures(ctx context.Context, query *ProductFeatureQuery, nodes []*LicenseType, init func(*LicenseType), assign func(*LicenseType, *ProductFeature)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*LicenseType)
	nids := make(map[int]map[*LicenseType]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(licensetype.FeaturesTable)
		s.Join(joinT).On(s.C(productfeature.FieldID), joinT.C(licensetype.FeaturesPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(licensetype.FeaturesPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(licensetype.FeaturesPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*LicenseType]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*ProductFeature](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "features" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (ltq *LicenseTypeQuery) loadDevices(ctx context.Context, query *DeviceQuery, nodes []*LicenseType, init func(*LicenseType), assign func(*LicenseType, *Device)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*LicenseType)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(device.FieldLicenseTypeID)
	}
	query.Where(predicate.Device(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(licensetype.DevicesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.LicenseTypeID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "license_type_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (ltq *LicenseTypeQuery) loadLicenseTypeFeatures(ctx context.Context, query *LicenseTypeFeaturesQuery, nodes []*LicenseType, init func(*LicenseType), assign func(*LicenseType, *LicenseTypeFeatures)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*LicenseType)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(licensetypefeatures.FieldLicenseTypeID)
	}
	query.Where(predicate.LicenseTypeFeatures(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(licensetype.LicenseTypeFeaturesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.LicenseTypeID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "license_type_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (ltq *LicenseTypeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ltq.querySpec()
	_spec.Node.Columns = ltq.ctx.Fields
	if len(ltq.ctx.Fields) > 0 {
		_spec.Unique = ltq.ctx.Unique != nil && *ltq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ltq.driver, _spec)
}

func (ltq *LicenseTypeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(licensetype.Table, licensetype.Columns, sqlgraph.NewFieldSpec(licensetype.FieldID, field.TypeInt))
	_spec.From = ltq.sql
	if unique := ltq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ltq.path != nil {
		_spec.Unique = true
	}
	if fields := ltq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, licensetype.FieldID)
		for i := range fields {
			if fields[i] != licensetype.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if ltq.withProduct != nil {
			_spec.Node.AddColumnOnce(licensetype.FieldProductID)
		}
	}
	if ps := ltq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ltq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ltq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ltq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ltq *LicenseTypeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ltq.driver.Dialect())
	t1 := builder.Table(licensetype.Table)
	columns := ltq.ctx.Fields
	if len(columns) == 0 {
		columns = licensetype.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ltq.sql != nil {
		selector = ltq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ltq.ctx.Unique != nil && *ltq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ltq.predicates {
		p(selector)
	}
	for _, p := range ltq.order {
		p(selector)
	}
	if offset := ltq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ltq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LicenseTypeGroupBy is the group-by builder for LicenseType entities.
type LicenseTypeGroupBy struct {
	selector
	build *LicenseTypeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ltgb *LicenseTypeGroupBy) Aggregate(fns ...AggregateFunc) *LicenseTypeGroupBy {
	ltgb.fns = append(ltgb.fns, fns...)
	return ltgb
}

// Scan applies the selector query and scans the result into the given value.
func (ltgb *LicenseTypeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ltgb.build.ctx, "GroupBy")
	if err := ltgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LicenseTypeQuery, *LicenseTypeGroupBy](ctx, ltgb.build, ltgb, ltgb.build.inters, v)
}

func (ltgb *LicenseTypeGroupBy) sqlScan(ctx context.Context, root *LicenseTypeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ltgb.fns))
	for _, fn := range ltgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ltgb.flds)+len(ltgb.fns))
		for _, f := range *ltgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ltgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ltgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LicenseTypeSelect is the builder for selecting fields of LicenseType entities.
type LicenseTypeSelect struct {
	*LicenseTypeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (lts *LicenseTypeSelect) Aggregate(fns ...AggregateFunc) *LicenseTypeSelect {
	lts.fns = append(lts.fns, fns...)
	return lts
}

// Scan applies the selector query and scans the result into the given value.
func (lts *LicenseTypeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lts.ctx, "Select")
	if err := lts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LicenseTypeQuery, *LicenseTypeSelect](ctx, lts.LicenseTypeQuery, lts, lts.inters, v)
}

func (lts *LicenseTypeSelect) sqlScan(ctx context.Context, root *LicenseTypeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(lts.fns))
	for _, fn := range lts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*lts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
