// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"cambridge-hit.com/gin-base/activateserver/app/entity/ent/post"
	"cambridge-hit.com/gin-base/activateserver/app/entity/ent/posttag"
	"cambridge-hit.com/gin-base/activateserver/app/entity/ent/posttagrelation"
	"cambridge-hit.com/gin-base/activateserver/app/entity/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PostTagRelationUpdate is the builder for updating PostTagRelation entities.
type PostTagRelationUpdate struct {
	config
	hooks    []Hook
	mutation *PostTagRelationMutation
}

// Where appends a list predicates to the PostTagRelationUpdate builder.
func (ptru *PostTagRelationUpdate) Where(ps ...predicate.PostTagRelation) *PostTagRelationUpdate {
	ptru.mutation.Where(ps...)
	return ptru
}

// SetPostID sets the "post_id" field.
func (ptru *PostTagRelationUpdate) SetPostID(i int) *PostTagRelationUpdate {
	ptru.mutation.SetPostID(i)
	return ptru
}

// SetPostTagID sets the "post_tag_id" field.
func (ptru *PostTagRelationUpdate) SetPostTagID(i int) *PostTagRelationUpdate {
	ptru.mutation.SetPostTagID(i)
	return ptru
}

// SetPost sets the "post" edge to the Post entity.
func (ptru *PostTagRelationUpdate) SetPost(p *Post) *PostTagRelationUpdate {
	return ptru.SetPostID(p.ID)
}

// SetPostTag sets the "post_tag" edge to the PostTag entity.
func (ptru *PostTagRelationUpdate) SetPostTag(p *PostTag) *PostTagRelationUpdate {
	return ptru.SetPostTagID(p.ID)
}

// Mutation returns the PostTagRelationMutation object of the builder.
func (ptru *PostTagRelationUpdate) Mutation() *PostTagRelationMutation {
	return ptru.mutation
}

// ClearPost clears the "post" edge to the Post entity.
func (ptru *PostTagRelationUpdate) ClearPost() *PostTagRelationUpdate {
	ptru.mutation.ClearPost()
	return ptru
}

// ClearPostTag clears the "post_tag" edge to the PostTag entity.
func (ptru *PostTagRelationUpdate) ClearPostTag() *PostTagRelationUpdate {
	ptru.mutation.ClearPostTag()
	return ptru
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ptru *PostTagRelationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ptru.sqlSave, ptru.mutation, ptru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ptru *PostTagRelationUpdate) SaveX(ctx context.Context) int {
	affected, err := ptru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ptru *PostTagRelationUpdate) Exec(ctx context.Context) error {
	_, err := ptru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ptru *PostTagRelationUpdate) ExecX(ctx context.Context) {
	if err := ptru.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ptru *PostTagRelationUpdate) check() error {
	if _, ok := ptru.mutation.PostID(); ptru.mutation.PostCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "PostTagRelation.post"`)
	}
	if _, ok := ptru.mutation.PostTagID(); ptru.mutation.PostTagCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "PostTagRelation.post_tag"`)
	}
	return nil
}

func (ptru *PostTagRelationUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ptru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(posttagrelation.Table, posttagrelation.Columns, sqlgraph.NewFieldSpec(posttagrelation.FieldID, field.TypeInt))
	if ps := ptru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if ptru.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   posttagrelation.PostTable,
			Columns: []string{posttagrelation.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ptru.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   posttagrelation.PostTable,
			Columns: []string{posttagrelation.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ptru.mutation.PostTagCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   posttagrelation.PostTagTable,
			Columns: []string{posttagrelation.PostTagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(posttag.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ptru.mutation.PostTagIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   posttagrelation.PostTagTable,
			Columns: []string{posttagrelation.PostTagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(posttag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ptru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{posttagrelation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ptru.mutation.done = true
	return n, nil
}

// PostTagRelationUpdateOne is the builder for updating a single PostTagRelation entity.
type PostTagRelationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PostTagRelationMutation
}

// SetPostID sets the "post_id" field.
func (ptruo *PostTagRelationUpdateOne) SetPostID(i int) *PostTagRelationUpdateOne {
	ptruo.mutation.SetPostID(i)
	return ptruo
}

// SetPostTagID sets the "post_tag_id" field.
func (ptruo *PostTagRelationUpdateOne) SetPostTagID(i int) *PostTagRelationUpdateOne {
	ptruo.mutation.SetPostTagID(i)
	return ptruo
}

// SetPost sets the "post" edge to the Post entity.
func (ptruo *PostTagRelationUpdateOne) SetPost(p *Post) *PostTagRelationUpdateOne {
	return ptruo.SetPostID(p.ID)
}

// SetPostTag sets the "post_tag" edge to the PostTag entity.
func (ptruo *PostTagRelationUpdateOne) SetPostTag(p *PostTag) *PostTagRelationUpdateOne {
	return ptruo.SetPostTagID(p.ID)
}

// Mutation returns the PostTagRelationMutation object of the builder.
func (ptruo *PostTagRelationUpdateOne) Mutation() *PostTagRelationMutation {
	return ptruo.mutation
}

// ClearPost clears the "post" edge to the Post entity.
func (ptruo *PostTagRelationUpdateOne) ClearPost() *PostTagRelationUpdateOne {
	ptruo.mutation.ClearPost()
	return ptruo
}

// ClearPostTag clears the "post_tag" edge to the PostTag entity.
func (ptruo *PostTagRelationUpdateOne) ClearPostTag() *PostTagRelationUpdateOne {
	ptruo.mutation.ClearPostTag()
	return ptruo
}

// Where appends a list predicates to the PostTagRelationUpdate builder.
func (ptruo *PostTagRelationUpdateOne) Where(ps ...predicate.PostTagRelation) *PostTagRelationUpdateOne {
	ptruo.mutation.Where(ps...)
	return ptruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ptruo *PostTagRelationUpdateOne) Select(field string, fields ...string) *PostTagRelationUpdateOne {
	ptruo.fields = append([]string{field}, fields...)
	return ptruo
}

// Save executes the query and returns the updated PostTagRelation entity.
func (ptruo *PostTagRelationUpdateOne) Save(ctx context.Context) (*PostTagRelation, error) {
	return withHooks(ctx, ptruo.sqlSave, ptruo.mutation, ptruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ptruo *PostTagRelationUpdateOne) SaveX(ctx context.Context) *PostTagRelation {
	node, err := ptruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ptruo *PostTagRelationUpdateOne) Exec(ctx context.Context) error {
	_, err := ptruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ptruo *PostTagRelationUpdateOne) ExecX(ctx context.Context) {
	if err := ptruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ptruo *PostTagRelationUpdateOne) check() error {
	if _, ok := ptruo.mutation.PostID(); ptruo.mutation.PostCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "PostTagRelation.post"`)
	}
	if _, ok := ptruo.mutation.PostTagID(); ptruo.mutation.PostTagCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "PostTagRelation.post_tag"`)
	}
	return nil
}

func (ptruo *PostTagRelationUpdateOne) sqlSave(ctx context.Context) (_node *PostTagRelation, err error) {
	if err := ptruo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(posttagrelation.Table, posttagrelation.Columns, sqlgraph.NewFieldSpec(posttagrelation.FieldID, field.TypeInt))
	id, ok := ptruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PostTagRelation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ptruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, posttagrelation.FieldID)
		for _, f := range fields {
			if !posttagrelation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != posttagrelation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ptruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if ptruo.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   posttagrelation.PostTable,
			Columns: []string{posttagrelation.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ptruo.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   posttagrelation.PostTable,
			Columns: []string{posttagrelation.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ptruo.mutation.PostTagCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   posttagrelation.PostTagTable,
			Columns: []string{posttagrelation.PostTagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(posttag.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ptruo.mutation.PostTagIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   posttagrelation.PostTagTable,
			Columns: []string{posttagrelation.PostTagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(posttag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PostTagRelation{config: ptruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ptruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{posttagrelation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ptruo.mutation.done = true
	return _node, nil
}
