// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"cambridge-hit.com/gin-base/activateserver/app/entity/ent/post"
	"cambridge-hit.com/gin-base/activateserver/app/entity/ent/posttag"
	"cambridge-hit.com/gin-base/activateserver/app/entity/ent/posttagrelation"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PostTagRelationCreate is the builder for creating a PostTagRelation entity.
type PostTagRelationCreate struct {
	config
	mutation *PostTagRelationMutation
	hooks    []Hook
}

// SetPostID sets the "post_id" field.
func (ptrc *PostTagRelationCreate) SetPostID(i int) *PostTagRelationCreate {
	ptrc.mutation.SetPostID(i)
	return ptrc
}

// SetPostTagID sets the "post_tag_id" field.
func (ptrc *PostTagRelationCreate) SetPostTagID(i int) *PostTagRelationCreate {
	ptrc.mutation.SetPostTagID(i)
	return ptrc
}

// SetCreatedAt sets the "created_at" field.
func (ptrc *PostTagRelationCreate) SetCreatedAt(t time.Time) *PostTagRelationCreate {
	ptrc.mutation.SetCreatedAt(t)
	return ptrc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ptrc *PostTagRelationCreate) SetNillableCreatedAt(t *time.Time) *PostTagRelationCreate {
	if t != nil {
		ptrc.SetCreatedAt(*t)
	}
	return ptrc
}

// SetID sets the "id" field.
func (ptrc *PostTagRelationCreate) SetID(i int) *PostTagRelationCreate {
	ptrc.mutation.SetID(i)
	return ptrc
}

// SetPost sets the "post" edge to the Post entity.
func (ptrc *PostTagRelationCreate) SetPost(p *Post) *PostTagRelationCreate {
	return ptrc.SetPostID(p.ID)
}

// SetPostTag sets the "post_tag" edge to the PostTag entity.
func (ptrc *PostTagRelationCreate) SetPostTag(p *PostTag) *PostTagRelationCreate {
	return ptrc.SetPostTagID(p.ID)
}

// Mutation returns the PostTagRelationMutation object of the builder.
func (ptrc *PostTagRelationCreate) Mutation() *PostTagRelationMutation {
	return ptrc.mutation
}

// Save creates the PostTagRelation in the database.
func (ptrc *PostTagRelationCreate) Save(ctx context.Context) (*PostTagRelation, error) {
	ptrc.defaults()
	return withHooks(ctx, ptrc.sqlSave, ptrc.mutation, ptrc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ptrc *PostTagRelationCreate) SaveX(ctx context.Context) *PostTagRelation {
	v, err := ptrc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ptrc *PostTagRelationCreate) Exec(ctx context.Context) error {
	_, err := ptrc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ptrc *PostTagRelationCreate) ExecX(ctx context.Context) {
	if err := ptrc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ptrc *PostTagRelationCreate) defaults() {
	if _, ok := ptrc.mutation.CreatedAt(); !ok {
		v := posttagrelation.DefaultCreatedAt()
		ptrc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ptrc *PostTagRelationCreate) check() error {
	if _, ok := ptrc.mutation.PostID(); !ok {
		return &ValidationError{Name: "post_id", err: errors.New(`ent: missing required field "PostTagRelation.post_id"`)}
	}
	if _, ok := ptrc.mutation.PostTagID(); !ok {
		return &ValidationError{Name: "post_tag_id", err: errors.New(`ent: missing required field "PostTagRelation.post_tag_id"`)}
	}
	if _, ok := ptrc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PostTagRelation.created_at"`)}
	}
	if v, ok := ptrc.mutation.ID(); ok {
		if err := posttagrelation.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "PostTagRelation.id": %w`, err)}
		}
	}
	if _, ok := ptrc.mutation.PostID(); !ok {
		return &ValidationError{Name: "post", err: errors.New(`ent: missing required edge "PostTagRelation.post"`)}
	}
	if _, ok := ptrc.mutation.PostTagID(); !ok {
		return &ValidationError{Name: "post_tag", err: errors.New(`ent: missing required edge "PostTagRelation.post_tag"`)}
	}
	return nil
}

func (ptrc *PostTagRelationCreate) sqlSave(ctx context.Context) (*PostTagRelation, error) {
	if err := ptrc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ptrc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ptrc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	ptrc.mutation.id = &_node.ID
	ptrc.mutation.done = true
	return _node, nil
}

func (ptrc *PostTagRelationCreate) createSpec() (*PostTagRelation, *sqlgraph.CreateSpec) {
	var (
		_node = &PostTagRelation{config: ptrc.config}
		_spec = sqlgraph.NewCreateSpec(posttagrelation.Table, sqlgraph.NewFieldSpec(posttagrelation.FieldID, field.TypeInt))
	)
	if id, ok := ptrc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ptrc.mutation.CreatedAt(); ok {
		_spec.SetField(posttagrelation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := ptrc.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   posttagrelation.PostTable,
			Columns: []string{posttagrelation.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PostID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ptrc.mutation.PostTagIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   posttagrelation.PostTagTable,
			Columns: []string{posttagrelation.PostTagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(posttag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PostTagID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PostTagRelationCreateBulk is the builder for creating many PostTagRelation entities in bulk.
type PostTagRelationCreateBulk struct {
	config
	err      error
	builders []*PostTagRelationCreate
}

// Save creates the PostTagRelation entities in the database.
func (ptrcb *PostTagRelationCreateBulk) Save(ctx context.Context) ([]*PostTagRelation, error) {
	if ptrcb.err != nil {
		return nil, ptrcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ptrcb.builders))
	nodes := make([]*PostTagRelation, len(ptrcb.builders))
	mutators := make([]Mutator, len(ptrcb.builders))
	for i := range ptrcb.builders {
		func(i int, root context.Context) {
			builder := ptrcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PostTagRelationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ptrcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ptrcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ptrcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ptrcb *PostTagRelationCreateBulk) SaveX(ctx context.Context) []*PostTagRelation {
	v, err := ptrcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ptrcb *PostTagRelationCreateBulk) Exec(ctx context.Context) error {
	_, err := ptrcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ptrcb *PostTagRelationCreateBulk) ExecX(ctx context.Context) {
	if err := ptrcb.Exec(ctx); err != nil {
		panic(err)
	}
}
