// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"cambridge-hit.com/gin-base/activateserver/app/entity/ent/post"
	"cambridge-hit.com/gin-base/activateserver/app/entity/ent/posttag"
	"cambridge-hit.com/gin-base/activateserver/app/entity/ent/posttagrelation"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// PostTagRelation is the model entity for the PostTagRelation schema.
type PostTagRelation struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 文章ID
	PostID int `json:"post_id,omitempty"`
	// 标签ID
	PostTagID int `json:"post_tag_id,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PostTagRelationQuery when eager-loading is set.
	Edges        PostTagRelationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PostTagRelationEdges holds the relations/edges for other nodes in the graph.
type PostTagRelationEdges struct {
	// Post holds the value of the post edge.
	Post *Post `json:"post,omitempty"`
	// PostTag holds the value of the post_tag edge.
	PostTag *PostTag `json:"post_tag,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PostOrErr returns the Post value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PostTagRelationEdges) PostOrErr() (*Post, error) {
	if e.loadedTypes[0] {
		if e.Post == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: post.Label}
		}
		return e.Post, nil
	}
	return nil, &NotLoadedError{edge: "post"}
}

// PostTagOrErr returns the PostTag value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PostTagRelationEdges) PostTagOrErr() (*PostTag, error) {
	if e.loadedTypes[1] {
		if e.PostTag == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: posttag.Label}
		}
		return e.PostTag, nil
	}
	return nil, &NotLoadedError{edge: "post_tag"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PostTagRelation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case posttagrelation.FieldID, posttagrelation.FieldPostID, posttagrelation.FieldPostTagID:
			values[i] = new(sql.NullInt64)
		case posttagrelation.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PostTagRelation fields.
func (ptr *PostTagRelation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case posttagrelation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ptr.ID = int(value.Int64)
		case posttagrelation.FieldPostID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field post_id", values[i])
			} else if value.Valid {
				ptr.PostID = int(value.Int64)
			}
		case posttagrelation.FieldPostTagID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field post_tag_id", values[i])
			} else if value.Valid {
				ptr.PostTagID = int(value.Int64)
			}
		case posttagrelation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ptr.CreatedAt = value.Time
			}
		default:
			ptr.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PostTagRelation.
// This includes values selected through modifiers, order, etc.
func (ptr *PostTagRelation) Value(name string) (ent.Value, error) {
	return ptr.selectValues.Get(name)
}

// QueryPost queries the "post" edge of the PostTagRelation entity.
func (ptr *PostTagRelation) QueryPost() *PostQuery {
	return NewPostTagRelationClient(ptr.config).QueryPost(ptr)
}

// QueryPostTag queries the "post_tag" edge of the PostTagRelation entity.
func (ptr *PostTagRelation) QueryPostTag() *PostTagQuery {
	return NewPostTagRelationClient(ptr.config).QueryPostTag(ptr)
}

// Update returns a builder for updating this PostTagRelation.
// Note that you need to call PostTagRelation.Unwrap() before calling this method if this PostTagRelation
// was returned from a transaction, and the transaction was committed or rolled back.
func (ptr *PostTagRelation) Update() *PostTagRelationUpdateOne {
	return NewPostTagRelationClient(ptr.config).UpdateOne(ptr)
}

// Unwrap unwraps the PostTagRelation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ptr *PostTagRelation) Unwrap() *PostTagRelation {
	_tx, ok := ptr.config.driver.(*txDriver)
	if !ok {
		panic("ent: PostTagRelation is not a transactional entity")
	}
	ptr.config.driver = _tx.drv
	return ptr
}

// String implements the fmt.Stringer.
func (ptr *PostTagRelation) String() string {
	var builder strings.Builder
	builder.WriteString("PostTagRelation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ptr.ID))
	builder.WriteString("post_id=")
	builder.WriteString(fmt.Sprintf("%v", ptr.PostID))
	builder.WriteString(", ")
	builder.WriteString("post_tag_id=")
	builder.WriteString(fmt.Sprintf("%v", ptr.PostTagID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(ptr.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PostTagRelations is a parsable slice of PostTagRelation.
type PostTagRelations []*PostTagRelation
