// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"cambridge-hit.com/gin-base/activateserver/app/entity/ent/posttagrelation"
	"cambridge-hit.com/gin-base/activateserver/app/entity/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PostTagRelationDelete is the builder for deleting a PostTagRelation entity.
type PostTagRelationDelete struct {
	config
	hooks    []Hook
	mutation *PostTagRelationMutation
}

// Where appends a list predicates to the PostTagRelationDelete builder.
func (ptrd *PostTagRelationDelete) Where(ps ...predicate.PostTagRelation) *PostTagRelationDelete {
	ptrd.mutation.Where(ps...)
	return ptrd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ptrd *PostTagRelationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ptrd.sqlExec, ptrd.mutation, ptrd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ptrd *PostTagRelationDelete) ExecX(ctx context.Context) int {
	n, err := ptrd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ptrd *PostTagRelationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(posttagrelation.Table, sqlgraph.NewFieldSpec(posttagrelation.FieldID, field.TypeInt))
	if ps := ptrd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ptrd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ptrd.mutation.done = true
	return affected, err
}

// PostTagRelationDeleteOne is the builder for deleting a single PostTagRelation entity.
type PostTagRelationDeleteOne struct {
	ptrd *PostTagRelationDelete
}

// Where appends a list predicates to the PostTagRelationDelete builder.
func (ptrdo *PostTagRelationDeleteOne) Where(ps ...predicate.PostTagRelation) *PostTagRelationDeleteOne {
	ptrdo.ptrd.mutation.Where(ps...)
	return ptrdo
}

// Exec executes the deletion query.
func (ptrdo *PostTagRelationDeleteOne) Exec(ctx context.Context) error {
	n, err := ptrdo.ptrd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{posttagrelation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ptrdo *PostTagRelationDeleteOne) ExecX(ctx context.Context) {
	if err := ptrdo.Exec(ctx); err != nil {
		panic(err)
	}
}
