// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"cambridge-hit.com/gin-base/activateserver/app/entity/ent/product"
	"cambridge-hit.com/gin-base/activateserver/app/entity/ent/softwareversion"
	"cambridge-hit.com/gin-base/activateserver/app/entity/ent/user"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// SoftwareVersion is the model entity for the SoftwareVersion schema.
type SoftwareVersion struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 产品ID
	ProductID int `json:"product_id,omitempty"`
	// 版本号
	Version string `json:"version,omitempty"`
	// 发布日期
	ReleaseDate time.Time `json:"release_date,omitempty"`
	// 更新日志
	UpdateLog string `json:"update_log,omitempty"`
	// 备注
	Remark string `json:"remark,omitempty"`
	// 创建人
	CreatedBy int `json:"created_by,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SoftwareVersionQuery when eager-loading is set.
	Edges        SoftwareVersionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SoftwareVersionEdges holds the relations/edges for other nodes in the graph.
type SoftwareVersionEdges struct {
	// 包含的功能列表
	Features []*ProductFeature `json:"features,omitempty"`
	// 兼容的韧件版本
	FirmwareVersions []*FirmwareVersion `json:"firmware_versions,omitempty"`
	// Product holds the value of the product edge.
	Product *Product `json:"product,omitempty"`
	// 创建人
	Creator *User `json:"creator,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// FeaturesOrErr returns the Features value or an error if the edge
// was not loaded in eager-loading.
func (e SoftwareVersionEdges) FeaturesOrErr() ([]*ProductFeature, error) {
	if e.loadedTypes[0] {
		return e.Features, nil
	}
	return nil, &NotLoadedError{edge: "features"}
}

// FirmwareVersionsOrErr returns the FirmwareVersions value or an error if the edge
// was not loaded in eager-loading.
func (e SoftwareVersionEdges) FirmwareVersionsOrErr() ([]*FirmwareVersion, error) {
	if e.loadedTypes[1] {
		return e.FirmwareVersions, nil
	}
	return nil, &NotLoadedError{edge: "firmware_versions"}
}

// ProductOrErr returns the Product value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SoftwareVersionEdges) ProductOrErr() (*Product, error) {
	if e.loadedTypes[2] {
		if e.Product == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: product.Label}
		}
		return e.Product, nil
	}
	return nil, &NotLoadedError{edge: "product"}
}

// CreatorOrErr returns the Creator value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SoftwareVersionEdges) CreatorOrErr() (*User, error) {
	if e.loadedTypes[3] {
		if e.Creator == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.Creator, nil
	}
	return nil, &NotLoadedError{edge: "creator"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SoftwareVersion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case softwareversion.FieldID, softwareversion.FieldProductID, softwareversion.FieldCreatedBy:
			values[i] = new(sql.NullInt64)
		case softwareversion.FieldVersion, softwareversion.FieldUpdateLog, softwareversion.FieldRemark:
			values[i] = new(sql.NullString)
		case softwareversion.FieldReleaseDate, softwareversion.FieldCreatedAt, softwareversion.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SoftwareVersion fields.
func (sv *SoftwareVersion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case softwareversion.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			sv.ID = int(value.Int64)
		case softwareversion.FieldProductID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field product_id", values[i])
			} else if value.Valid {
				sv.ProductID = int(value.Int64)
			}
		case softwareversion.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				sv.Version = value.String
			}
		case softwareversion.FieldReleaseDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field release_date", values[i])
			} else if value.Valid {
				sv.ReleaseDate = value.Time
			}
		case softwareversion.FieldUpdateLog:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field update_log", values[i])
			} else if value.Valid {
				sv.UpdateLog = value.String
			}
		case softwareversion.FieldRemark:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remark", values[i])
			} else if value.Valid {
				sv.Remark = value.String
			}
		case softwareversion.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				sv.CreatedBy = int(value.Int64)
			}
		case softwareversion.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				sv.CreatedAt = value.Time
			}
		case softwareversion.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				sv.UpdatedAt = value.Time
			}
		default:
			sv.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SoftwareVersion.
// This includes values selected through modifiers, order, etc.
func (sv *SoftwareVersion) Value(name string) (ent.Value, error) {
	return sv.selectValues.Get(name)
}

// QueryFeatures queries the "features" edge of the SoftwareVersion entity.
func (sv *SoftwareVersion) QueryFeatures() *ProductFeatureQuery {
	return NewSoftwareVersionClient(sv.config).QueryFeatures(sv)
}

// QueryFirmwareVersions queries the "firmware_versions" edge of the SoftwareVersion entity.
func (sv *SoftwareVersion) QueryFirmwareVersions() *FirmwareVersionQuery {
	return NewSoftwareVersionClient(sv.config).QueryFirmwareVersions(sv)
}

// QueryProduct queries the "product" edge of the SoftwareVersion entity.
func (sv *SoftwareVersion) QueryProduct() *ProductQuery {
	return NewSoftwareVersionClient(sv.config).QueryProduct(sv)
}

// QueryCreator queries the "creator" edge of the SoftwareVersion entity.
func (sv *SoftwareVersion) QueryCreator() *UserQuery {
	return NewSoftwareVersionClient(sv.config).QueryCreator(sv)
}

// Update returns a builder for updating this SoftwareVersion.
// Note that you need to call SoftwareVersion.Unwrap() before calling this method if this SoftwareVersion
// was returned from a transaction, and the transaction was committed or rolled back.
func (sv *SoftwareVersion) Update() *SoftwareVersionUpdateOne {
	return NewSoftwareVersionClient(sv.config).UpdateOne(sv)
}

// Unwrap unwraps the SoftwareVersion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sv *SoftwareVersion) Unwrap() *SoftwareVersion {
	_tx, ok := sv.config.driver.(*txDriver)
	if !ok {
		panic("ent: SoftwareVersion is not a transactional entity")
	}
	sv.config.driver = _tx.drv
	return sv
}

// String implements the fmt.Stringer.
func (sv *SoftwareVersion) String() string {
	var builder strings.Builder
	builder.WriteString("SoftwareVersion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", sv.ID))
	builder.WriteString("product_id=")
	builder.WriteString(fmt.Sprintf("%v", sv.ProductID))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(sv.Version)
	builder.WriteString(", ")
	builder.WriteString("release_date=")
	builder.WriteString(sv.ReleaseDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_log=")
	builder.WriteString(sv.UpdateLog)
	builder.WriteString(", ")
	builder.WriteString("remark=")
	builder.WriteString(sv.Remark)
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", sv.CreatedBy))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(sv.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(sv.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SoftwareVersions is a parsable slice of SoftwareVersion.
type SoftwareVersions []*SoftwareVersion
