// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"cambridge-hit.com/gin-base/activateserver/app/entity/ent/predicate"
	"cambridge-hit.com/gin-base/activateserver/app/entity/ent/softwareversion"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SoftwareVersionDelete is the builder for deleting a SoftwareVersion entity.
type SoftwareVersionDelete struct {
	config
	hooks    []Hook
	mutation *SoftwareVersionMutation
}

// Where appends a list predicates to the SoftwareVersionDelete builder.
func (svd *SoftwareVersionDelete) Where(ps ...predicate.SoftwareVersion) *SoftwareVersionDelete {
	svd.mutation.Where(ps...)
	return svd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (svd *SoftwareVersionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, svd.sqlExec, svd.mutation, svd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (svd *SoftwareVersionDelete) ExecX(ctx context.Context) int {
	n, err := svd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (svd *SoftwareVersionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(softwareversion.Table, sqlgraph.NewFieldSpec(softwareversion.FieldID, field.TypeInt))
	if ps := svd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, svd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	svd.mutation.done = true
	return affected, err
}

// SoftwareVersionDeleteOne is the builder for deleting a single SoftwareVersion entity.
type SoftwareVersionDeleteOne struct {
	svd *SoftwareVersionDelete
}

// Where appends a list predicates to the SoftwareVersionDelete builder.
func (svdo *SoftwareVersionDeleteOne) Where(ps ...predicate.SoftwareVersion) *SoftwareVersionDeleteOne {
	svdo.svd.mutation.Where(ps...)
	return svdo
}

// Exec executes the deletion query.
func (svdo *SoftwareVersionDeleteOne) Exec(ctx context.Context) error {
	n, err := svdo.svd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{softwareversion.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (svdo *SoftwareVersionDeleteOne) ExecX(ctx context.Context) {
	if err := svdo.Exec(ctx); err != nil {
		panic(err)
	}
}
