// Code generated by ent, DO NOT EDIT.

package posttagrelation

import (
	"time"

	"cambridge-hit.com/gin-base/activateserver/app/entity/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PostTagRelation {
	return predicate.PostTagRelation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PostTagRelation {
	return predicate.PostTagRelation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PostTagRelation {
	return predicate.PostTagRelation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PostTagRelation {
	return predicate.PostTagRelation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PostTagRelation {
	return predicate.PostTagRelation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PostTagRelation {
	return predicate.PostTagRelation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PostTagRelation {
	return predicate.PostTagRelation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PostTagRelation {
	return predicate.PostTagRelation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PostTagRelation {
	return predicate.PostTagRelation(sql.FieldLTE(FieldID, id))
}

// PostID applies equality check predicate on the "post_id" field. It's identical to PostIDEQ.
func PostID(v int) predicate.PostTagRelation {
	return predicate.PostTagRelation(sql.FieldEQ(FieldPostID, v))
}

// PostTagID applies equality check predicate on the "post_tag_id" field. It's identical to PostTagIDEQ.
func PostTagID(v int) predicate.PostTagRelation {
	return predicate.PostTagRelation(sql.FieldEQ(FieldPostTagID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PostTagRelation {
	return predicate.PostTagRelation(sql.FieldEQ(FieldCreatedAt, v))
}

// PostIDEQ applies the EQ predicate on the "post_id" field.
func PostIDEQ(v int) predicate.PostTagRelation {
	return predicate.PostTagRelation(sql.FieldEQ(FieldPostID, v))
}

// PostIDNEQ applies the NEQ predicate on the "post_id" field.
func PostIDNEQ(v int) predicate.PostTagRelation {
	return predicate.PostTagRelation(sql.FieldNEQ(FieldPostID, v))
}

// PostIDIn applies the In predicate on the "post_id" field.
func PostIDIn(vs ...int) predicate.PostTagRelation {
	return predicate.PostTagRelation(sql.FieldIn(FieldPostID, vs...))
}

// PostIDNotIn applies the NotIn predicate on the "post_id" field.
func PostIDNotIn(vs ...int) predicate.PostTagRelation {
	return predicate.PostTagRelation(sql.FieldNotIn(FieldPostID, vs...))
}

// PostTagIDEQ applies the EQ predicate on the "post_tag_id" field.
func PostTagIDEQ(v int) predicate.PostTagRelation {
	return predicate.PostTagRelation(sql.FieldEQ(FieldPostTagID, v))
}

// PostTagIDNEQ applies the NEQ predicate on the "post_tag_id" field.
func PostTagIDNEQ(v int) predicate.PostTagRelation {
	return predicate.PostTagRelation(sql.FieldNEQ(FieldPostTagID, v))
}

// PostTagIDIn applies the In predicate on the "post_tag_id" field.
func PostTagIDIn(vs ...int) predicate.PostTagRelation {
	return predicate.PostTagRelation(sql.FieldIn(FieldPostTagID, vs...))
}

// PostTagIDNotIn applies the NotIn predicate on the "post_tag_id" field.
func PostTagIDNotIn(vs ...int) predicate.PostTagRelation {
	return predicate.PostTagRelation(sql.FieldNotIn(FieldPostTagID, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PostTagRelation {
	return predicate.PostTagRelation(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PostTagRelation {
	return predicate.PostTagRelation(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PostTagRelation {
	return predicate.PostTagRelation(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PostTagRelation {
	return predicate.PostTagRelation(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PostTagRelation {
	return predicate.PostTagRelation(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PostTagRelation {
	return predicate.PostTagRelation(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PostTagRelation {
	return predicate.PostTagRelation(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PostTagRelation {
	return predicate.PostTagRelation(sql.FieldLTE(FieldCreatedAt, v))
}

// HasPost applies the HasEdge predicate on the "post" edge.
func HasPost() predicate.PostTagRelation {
	return predicate.PostTagRelation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PostTable, PostColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPostWith applies the HasEdge predicate on the "post" edge with a given conditions (other predicates).
func HasPostWith(preds ...predicate.Post) predicate.PostTagRelation {
	return predicate.PostTagRelation(func(s *sql.Selector) {
		step := newPostStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPostTag applies the HasEdge predicate on the "post_tag" edge.
func HasPostTag() predicate.PostTagRelation {
	return predicate.PostTagRelation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PostTagTable, PostTagColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPostTagWith applies the HasEdge predicate on the "post_tag" edge with a given conditions (other predicates).
func HasPostTagWith(preds ...predicate.PostTag) predicate.PostTagRelation {
	return predicate.PostTagRelation(func(s *sql.Selector) {
		step := newPostTagStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PostTagRelation) predicate.PostTagRelation {
	return predicate.PostTagRelation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PostTagRelation) predicate.PostTagRelation {
	return predicate.PostTagRelation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PostTagRelation) predicate.PostTagRelation {
	return predicate.PostTagRelation(sql.NotPredicates(p))
}
