// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/activate/audit/list": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "audit"
                ],
                "summary": "获取操作日志列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码，从1开始",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "模块名称",
                        "name": "module",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "操作类型",
                        "name": "operation",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "操作用户ID",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "开始时间",
                        "name": "start_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "结束时间",
                        "name": "end_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取操作日志列表",
                        "schema": {
                            "$ref": "#/definitions/resp.Response"
                        }
                    }
                }
            }
        },
        "/activate/base/login": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Base"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "参数：用户登录",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UserLoginInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "用户登录",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/resp.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/activate/base/register": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Base"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "参数：用户注册",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UserLoginInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "用户注册",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/resp.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/activate/device/activation-file/{sn}": {
            "get": {
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "device"
                ],
                "summary": "获取设备激活文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "产品ID",
                        "name": "productID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "设备序列号",
                        "name": "sn",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "激活文件",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/activate/device/add": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "添加单个设备",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "参数：添加设备",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DeviceAdd"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "添加设备",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/resp.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/activate/device/batch-add": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "批量添加设备",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "参数：批量添加设备",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DeviceBatchAdd"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "批量添加设备",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/resp.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/activate/device/batch-update-license": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "批量更新设备许可证类型",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "参数：批量更新许可证类型",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DeviceBatchUpdateLicense"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "批量更新许可证类型",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/resp.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/activate/device/license-types": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "获取产品下的许可证类型列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "产品ID",
                        "name": "product_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取许可证类型列表",
                        "schema": {
                            "$ref": "#/definitions/resp.Response"
                        }
                    }
                }
            }
        },
        "/activate/device/list": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "获取产品下的设备列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "产品ID",
                        "name": "product_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "许可证类型ID",
                        "name": "license_type_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "设备序列号",
                        "name": "sn",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码，从1开始",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取设备列表",
                        "schema": {
                            "$ref": "#/definitions/resp.Response"
                        }
                    }
                }
            }
        },
        "/activate/device/products": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "获取产品列表（带设备数量）",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码，从1开始",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取产品列表",
                        "schema": {
                            "$ref": "#/definitions/resp.Response"
                        }
                    }
                }
            }
        },
        "/activate/device/search": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "通过SN获取设备信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "设备序列号",
                        "name": "sn",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取设备信息",
                        "schema": {
                            "$ref": "#/definitions/resp.Response"
                        }
                    }
                }
            }
        },
        "/activate/device/update": {
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "更新设备",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "参数：更新设备",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DeviceUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新设备",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/resp.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/activate/device/{id}": {
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "删除设备",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "设备ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除设备",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/resp.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/activate/firmware-versions": {
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "version"
                ],
                "summary": "修改韧件版本",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "参数：修改韧件版本",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ModifyFirmwareVersion"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "修改韧件版本",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/resp.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "version"
                ],
                "summary": "添加韧件版本",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "参数：添加韧件版本",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AddFirmwareVersion"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "添加韧件版本",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/resp.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/activate/firmware-versions/{id}": {
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "version"
                ],
                "summary": "删除韧件版本",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "韧件版本ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除韧件版本",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/resp.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/activate/firmware-versions/{product_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "version"
                ],
                "summary": "获取韧件版本列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "产品ID",
                        "name": "product_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码，从1开始",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取韧件版本列表",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/resp.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/dto.PageResult"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "list": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/dto.FirmwareVersionResponse"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/activate/license-type/add": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LicenseType"
                ],
                "summary": "添加许可证类型",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "添加许可证类型参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AddLicenseType"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "添加许可证类型",
                        "schema": {
                            "$ref": "#/definitions/resp.Response"
                        }
                    }
                }
            }
        },
        "/activate/license-type/del": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LicenseType"
                ],
                "summary": "删除许可证类型",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "类型ID",
                        "name": "type_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除许可证类型",
                        "schema": {
                            "$ref": "#/definitions/resp.Response"
                        }
                    }
                }
            }
        },
        "/activate/license-type/list": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LicenseType"
                ],
                "summary": "获取许可证类型列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "产品ID",
                        "name": "product_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码，从1开始",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取许可证类型列表",
                        "schema": {
                            "$ref": "#/definitions/resp.Response"
                        }
                    }
                }
            }
        },
        "/activate/license-type/update-features": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LicenseType"
                ],
                "summary": "更新许可证类型功能列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "更新许可证类型功能列表参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateLicenseTypeFeatures"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新许可证类型功能列表",
                        "schema": {
                            "$ref": "#/definitions/resp.Response"
                        }
                    }
                }
            }
        },
        "/activate/product-feature/add": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ProductFeature"
                ],
                "summary": "添加产品功能",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "添加产品功能参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AddProductFeature"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "添加产品功能",
                        "schema": {
                            "$ref": "#/definitions/resp.Response"
                        }
                    }
                }
            }
        },
        "/activate/product-feature/del": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ProductFeature"
                ],
                "summary": "删除产品功能",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "功能ID",
                        "name": "feature_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除产品功能",
                        "schema": {
                            "$ref": "#/definitions/resp.Response"
                        }
                    }
                }
            }
        },
        "/activate/product-feature/list": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ProductFeature"
                ],
                "summary": "获取产品功能列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "产品ID",
                        "name": "product_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码，从1开始",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取产品功能列表",
                        "schema": {
                            "$ref": "#/definitions/resp.Response"
                        }
                    }
                }
            }
        },
        "/activate/product/add": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "增加产品",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "参数：增加产品",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AddProduct"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "增加产品",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/resp.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/activate/product/add-manager": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "添加产品管理员",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "参数：添加产品管理员",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AddManager"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "添加产品管理员",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/resp.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/activate/product/del": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "删除产品",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "产品ID",
                        "name": "product_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除产品",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/resp.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/activate/product/list": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "product"
                ],
                "summary": "获取用户的产品列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码，从1开始",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取产品列表",
                        "schema": {
                            "$ref": "#/definitions/resp.Response"
                        }
                    }
                }
            }
        },
        "/activate/product/put": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "修改产品",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "参数：修改产品",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ModifyProduct"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "修改产品",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/resp.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/activate/product/remove-manager": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "删除产品管理员",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "管理员ID",
                        "name": "manager_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除产品管理员",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/resp.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/activate/software-versions": {
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "version"
                ],
                "summary": "修改软件版本",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "参数：修改软件版本",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ModifySoftwareVersion"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "修改软件版本",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/resp.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "version"
                ],
                "summary": "添加软件版本",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "参数：添加软件版本",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AddSoftwareVersion"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "添加软件版本",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/resp.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/activate/software-versions/{id}": {
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "version"
                ],
                "summary": "删除软件版本",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "软件版本ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除软件版本",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/resp.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/activate/software-versions/{product_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "version"
                ],
                "summary": "获取软件版本列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "产品ID",
                        "name": "product_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码，从1开始",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取软件版本列表",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/resp.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/dto.PageResult"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "list": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/dto.SoftwareVersionResponse"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/activate/version/features/{product_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "version"
                ],
                "summary": "获取产品的所有功能",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "产品ID",
                        "name": "product_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取产品功能列表",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/resp.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.FeatureInfo"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/activate/version/firmware/all/{product_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "version"
                ],
                "summary": "获取产品的所有韧件版本",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "产品ID",
                        "name": "product_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取产品韧件版本列表",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/resp.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.FirmwareInfo"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AddFirmwareVersion": {
            "type": "object",
            "required": [
                "product_id",
                "release_date",
                "version"
            ],
            "properties": {
                "product_id": {
                    "description": "产品ID",
                    "type": "integer"
                },
                "release_date": {
                    "description": "发布日期",
                    "type": "string"
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                },
                "version": {
                    "description": "韧件版本号",
                    "type": "string"
                }
            }
        },
        "dto.AddLicenseType": {
            "type": "object",
            "required": [
                "license_type",
                "product_id",
                "type_name"
            ],
            "properties": {
                "feature_ids": {
                    "description": "功能ID列表",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "license_type": {
                    "description": "许可证编码",
                    "type": "string"
                },
                "product_id": {
                    "description": "产品ID",
                    "type": "integer"
                },
                "type_name": {
                    "description": "许可证类型名称",
                    "type": "string"
                }
            }
        },
        "dto.AddManager": {
            "type": "object",
            "required": [
                "email",
                "product_id"
            ],
            "properties": {
                "email": {
                    "description": "用户邮箱",
                    "type": "string"
                },
                "permissions": {
                    "description": "权限 (read/full)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/productmanager.Permissions"
                        }
                    ]
                },
                "product_id": {
                    "description": "产品ID",
                    "type": "integer"
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                }
            }
        },
        "dto.AddProduct": {
            "type": "object",
            "required": [
                "code",
                "product_name",
                "product_type"
            ],
            "properties": {
                "code": {
                    "description": "ID          int    ` + "`" + `json:\"id,omitempty\"` + "`" + `                    //指定产品id",
                    "type": "string"
                },
                "product_name": {
                    "description": "产品名称",
                    "type": "string"
                },
                "product_type": {
                    "description": "产品名称",
                    "type": "string"
                }
            }
        },
        "dto.AddProductFeature": {
            "type": "object",
            "required": [
                "feature_code",
                "feature_name",
                "product_id"
            ],
            "properties": {
                "feature_code": {
                    "description": "功能编码",
                    "type": "string"
                },
                "feature_name": {
                    "description": "功能名称",
                    "type": "string"
                },
                "product_id": {
                    "description": "产品ID",
                    "type": "integer"
                }
            }
        },
        "dto.AddSoftwareVersion": {
            "type": "object",
            "required": [
                "product_id",
                "release_date",
                "version"
            ],
            "properties": {
                "feature_ids": {
                    "description": "功能ID列表",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "firmware_ids": {
                    "description": "兼容的韧件版本ID列表",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "product_id": {
                    "description": "产品ID",
                    "type": "integer"
                },
                "release_date": {
                    "description": "发布日期",
                    "type": "string"
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                },
                "update_log": {
                    "description": "更新日志",
                    "type": "string"
                },
                "version": {
                    "description": "软件版本号",
                    "type": "string"
                }
            }
        },
        "dto.DeviceAdd": {
            "type": "object",
            "required": [
                "license_type_id",
                "product_id",
                "sn"
            ],
            "properties": {
                "license_type_id": {
                    "type": "integer"
                },
                "oem_tag": {
                    "type": "string"
                },
                "product_id": {
                    "type": "integer"
                },
                "remark": {
                    "type": "string"
                },
                "sn": {
                    "type": "string"
                }
            }
        },
        "dto.DeviceBatchAdd": {
            "type": "object",
            "required": [
                "license_type_id",
                "product_id",
                "sns"
            ],
            "properties": {
                "license_type_id": {
                    "type": "integer"
                },
                "oem_tag": {
                    "type": "string"
                },
                "product_id": {
                    "type": "integer"
                },
                "remark": {
                    "type": "string"
                },
                "sns": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dto.DeviceBatchUpdateLicense": {
            "type": "object",
            "required": [
                "device_ids",
                "license_type_id"
            ],
            "properties": {
                "device_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "license_type_id": {
                    "type": "integer"
                },
                "remark": {
                    "type": "string"
                }
            }
        },
        "dto.DeviceUpdate": {
            "type": "object",
            "required": [
                "id",
                "license_type_id"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "license_type_id": {
                    "type": "integer"
                },
                "oem_tag": {
                    "type": "string"
                },
                "remark": {
                    "type": "string"
                }
            }
        },
        "dto.FeatureInfo": {
            "type": "object",
            "properties": {
                "feature_code": {
                    "description": "功能编码",
                    "type": "string"
                },
                "feature_name": {
                    "description": "功能名称",
                    "type": "string"
                },
                "id": {
                    "description": "功能ID",
                    "type": "integer"
                }
            }
        },
        "dto.FirmwareInfo": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "韧件版本ID",
                    "type": "integer"
                },
                "release_date": {
                    "description": "发布日期",
                    "type": "string"
                },
                "version": {
                    "description": "韧件版本号",
                    "type": "string"
                }
            }
        },
        "dto.FirmwareVersionResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "created_by": {
                    "description": "创建者ID",
                    "type": "integer"
                },
                "created_by_email": {
                    "description": "创建者邮箱",
                    "type": "string"
                },
                "id": {
                    "description": "韧件版本ID",
                    "type": "integer"
                },
                "product_id": {
                    "description": "产品ID",
                    "type": "integer"
                },
                "release_date": {
                    "description": "发布日期",
                    "type": "string"
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                },
                "version": {
                    "description": "韧件版本号",
                    "type": "string"
                }
            }
        },
        "dto.ModifyFirmwareVersion": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "description": "韧件版本ID",
                    "type": "integer"
                },
                "release_date": {
                    "description": "发布日期",
                    "type": "string"
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                },
                "version": {
                    "description": "韧件版本号",
                    "type": "string"
                }
            }
        },
        "dto.ModifyProduct": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "description": "产品id不可空",
                    "type": "integer"
                },
                "manager_assistant": {
                    "description": "副管理员",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.productAssistant"
                    }
                },
                "manager_main": {
                    "description": "主管理员",
                    "type": "integer"
                },
                "product_name": {
                    "description": "Code        string ` + "`" + `json:\"code\" binding:\"required\"` + "`" + `         // 产品代号不允许修改",
                    "type": "string"
                },
                "product_type": {
                    "description": "产品类别",
                    "type": "string"
                }
            }
        },
        "dto.ModifySoftwareVersion": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "feature_ids": {
                    "description": "功能ID列表",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "firmware_ids": {
                    "description": "兼容的韧件版本ID列表",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "id": {
                    "description": "软件版本ID",
                    "type": "integer"
                },
                "release_date": {
                    "description": "发布日期",
                    "type": "string"
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                },
                "update_log": {
                    "description": "更新日志",
                    "type": "string"
                },
                "version": {
                    "description": "软件版本号",
                    "type": "string"
                }
            }
        },
        "dto.PageResult": {
            "type": "object",
            "properties": {
                "extra": {
                    "description": "额外数据",
                    "type": "object",
                    "additionalProperties": true
                },
                "list": {
                    "description": "数据列表"
                },
                "page": {
                    "description": "当前页码",
                    "type": "integer"
                },
                "page_size": {
                    "description": "每页数量",
                    "type": "integer"
                },
                "total": {
                    "description": "总记录数",
                    "type": "integer"
                }
            }
        },
        "dto.SoftwareVersionResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "created_by": {
                    "description": "创建者ID",
                    "type": "integer"
                },
                "created_by_email": {
                    "description": "创建者邮箱",
                    "type": "string"
                },
                "features": {
                    "description": "功能列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.FeatureInfo"
                    }
                },
                "firmwares": {
                    "description": "兼容的韧件版本列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.FirmwareInfo"
                    }
                },
                "id": {
                    "description": "软件版本ID",
                    "type": "integer"
                },
                "product_id": {
                    "description": "产品ID",
                    "type": "integer"
                },
                "release_date": {
                    "description": "发布日期",
                    "type": "string"
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                },
                "update_log": {
                    "description": "更新日志",
                    "type": "string"
                },
                "version": {
                    "description": "软件版本号",
                    "type": "string"
                }
            }
        },
        "dto.UpdateLicenseTypeFeatures": {
            "type": "object",
            "required": [
                "type_id"
            ],
            "properties": {
                "feature_ids": {
                    "description": "功能ID列表",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "type_id": {
                    "description": "许可证类型ID",
                    "type": "integer"
                }
            }
        },
        "dto.UserLoginInfo": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "dto.productAssistant": {
            "type": "object",
            "properties": {
                "permission": {
                    "$ref": "#/definitions/productmanager.Permissions"
                },
                "remark": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "productmanager.Permissions": {
            "type": "string",
            "enum": [
                "read",
                "read",
                "full"
            ],
            "x-enum-varnames": [
                "DefaultPermissions",
                "PermissionsRead",
                "PermissionsFull"
            ]
        },
        "resp.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
